defaults:
  data_dir: 'data/raw/{}'
  feature_path: 'data/interim/{}_feat.h5'
  map_file: 'data/interim/{}_map.pkl'
hparams:
  window_size: 25
  window_shift: 10
  window_type: 'hann'
  sample_freq: 16000
