defaults:
  data_dir: 'data/raw/{}/{}'
  feature_path: 'data/interim/{}_feat.h5'
  map_file: 'data/interim/{}_map.pkl'
  save_path: 'models/checkpoints/{}'
  save_format: '%Y-%b-%d-%H:%M:%S'
hparams:
  window_size: 25
  window_shift: 10
  window_type: 'hann'
  num_workers: 1
  sample_freq: 16000
  l2_coeff: 0.001
  num_classes: 1252
  batch_size: 32
  learning_rate: 0.0001
  epochs: 30
  adam_eps: 0.001
  sched_decay: 0.9
  val_step: 500
  val_start: 499
